[workspace]
resolver = "2"
members = [
    "macros", "nalfecs"]

default-members = ["nalfecs"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
quote = "1.0.47"
proc-macro2 = "1.0.107"
syn = "3.0.3"
parking_lot = "0.12.5"
tokio = "1.34.0"
rand = "0.10.2"
trybuild = "1.0.120"
