[package]
name = "nalfecs"
version.workspace = true
edition.workspace = true
license = "MIT"
description = "The crate provides tools to create structure of arrays for game objects."
readme = "README.md"
keywords = ["soa", "structure-of-arrays", "game"]

[dependencies]
parking_lot.workspace = true

macros = { path = "../macros" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
rand.workspace = true
trybuild.workspace = true
